mode: train
train:
  dataset: MvRgbDatasetCustom
  data:
    subject_name: 5min_data
    data_dir: /dellnas/dataset/xiaomi_test/docker_upload/volcap/5min_data
    used_cam_ids: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32]
    load_smpl_pos_map: true
  pretrained_dir: null
  net_ckpt_dir: ./results/5min_data/avatar
  prev_ckpt: null
  pretrain_steps: 5000
  pretrain_eval_interval: 1000
  iter_num: 800000
  ckpt_interval:
    epoch: 10
    batch: 50000
  eval_interval: 1000
  eval_img_factor: 1.0
  lr_init: 0.0005
  loss_weight:
    l1: 1.0
    lpips: 0.1
    offset: 0.005
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true
test:
  dataset: MvRgbDatasetCustom
  data:
    subject_name: 5min_data
    data_dir: /dellnas/dataset/xiaomi_test/docker_upload/volcap/5min_data
    # frame_range: [0, 500]
    # pose_pkl: smpl_params_short.pkl
    used_cam_ids: [29]
    load_smpl_pos_map: true
  view_setting: camera
  render_view_idx: 29
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/5min_data/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false